### ISSUE TITLE
NFR: Add Dealer Locator Export Market from AU

### ISSUE THREAD

**Issue by jonatan-lledo-netcentric** [hlxsites/vg-macktrucks-cl#12]
use the same export market template used to create the one for AU updating the location to Chile coordinates and also update the JSON file with mock-up data

**Comment by girishdigrajkar** [comment]
Validated for find a dealer with set of dealers and content task for dealers will take care of all list of dealers. This ticket focus is for find a dealer functionality and able to see it working correctly hence, closing the ticket:

<img width="1792" alt="image" src="https://github.com/hlxsites/vg-macktrucks-cl/assets/125972657/56d77f25-eabe-4a83-987b-aa49742067f5">
