### ISSUE TITLE
Testing: Site testing for MackTrucks CL (QA & UAT)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-cl#2]
Testing in full all pages/sections of the site. This issue is for both QA testing and UAT.

**Comment by shirin27** [comment]
As discussed with @BeckyMedlin , the testing tickets are out of scope for the Netcentric team and will be assigned to CMS team.

**Comment by Kannan-CM** [comment]
Related to OneTrust scanning...

**Comment by Kannan-CM** [comment]
Content migrated
