### ISSUE TITLE
NFR: Configure analytics/tracking

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-macktrucks-cl#7]
This is part of the GoLive activities.

Configure analytics/tracking (GTM, FB Pixel if needed, and OneTrust)

**Comment by manuel-vara** [comment]
Chile would be using same GTM code as Mexico

**Comment by jonatan-lledo-netcentric** [comment]
same as Mexico:
#
oneTrust id?
is hotjar needed? if so, id?
is fb pixel needed? if so, id?
please @Kannan-CM can you add a comment with the IDs? thanks

**Comment by Kannan-CM** [comment]
<script src="https://cdn.cookielaw.org/scripttemplates/otSDKStub.js"  type="text/javascript" charset="UTF-8" data-domain-script="649112e3-1b0c-43bc-8cce-93088ac17e81" ></script>
<script type="text/javascript">
function OptanonWrapper() { }
</script>

**Comment by Kannan-CM** [comment]
<button id="ot-sdk-btn" class="ot-sdk-show-settings">Cookie Settings</button>
